version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: auctions_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB:       ${DB_NAME:-auctions_service_db}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auctions-service:
    build: .
    container_name: auctions_service_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT:        3003
      DB_HOST:     postgres
      DB_PORT:     5432
      DB_NAME:     ${DB_NAME:-auctions_service_db}
      DB_USER:     ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL:-http://host.docker.internal:3004}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3003:3003"

volumes:
  postgres_data:
